"""Database kernel: engines, session factories, tables and migrations (docs/dev-guide.md §5.2)."""

from __future__ import annotations

from uuid import UUID

import uuid_utils


def new_id() -> UUID:
    """A UUIDv7 surrogate id, generated by the application and never by the database (04 NC-04)."""
    return UUID(bytes=uuid_utils.uuid7().bytes)
