"""API-R-20 account mapping schemas (04 §15.3 API-R-20, T-REF-14, T-REF-15, E-01, E-109, §16.14 list
additions; SCREENS §9.6 mapping data bindings; BUILD_SPEC RFD-7).

04 §16 defines no account mapping schema. A version follows the T-REF-14 and SC-V columns plus
``pending_approval_request_id``, ``rule_count`` (§16.14), ``created_at``, ``updated_at`` and
``row_version``; a rule follows the T-REF-15 columns and names its GL account as API-S-Ref for the
grid's "<code> <name>" column (L2-1-Q-1). ``specificity`` is generated by the database.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Final, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from erev_api.enums import AccountRole, BookCode, ClearingPurpose, ConfigStatus
from erev_api.schemas.common import ActorOut, RefOut
from erev_api.schemas.roles import CODE_LENGTH
from erev_api.schemas.users import LABEL_LENGTH, MEMO_LENGTH

INT_MIN: Final = -2_147_483_648
INT_MAX: Final = 2_147_483_647
SourceType = Literal["obligation_override", "template_override", "account_mapping_rule"]


class AccountMappingIn(BaseModel):
    """``POST /account-mappings``: the next version as DRAFT, optionally copying a version's
    rules."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(max_length=LABEL_LENGTH)
    notes: str | None = Field(default=None, max_length=MEMO_LENGTH)
    # MAIN DEFECT 4: the column is timestamptz (04 SC-V); a naive value used to reach the audit
    # canonicaliser and answer 500 — it is refused here with 422 like pob_templates / imports.
    effective_from: AwareDatetime | None = Field(
        default=None, description="Required before submission; frozen afterwards (DB-04)"
    )
    source_version_id: uuid.UUID | None = Field(
        default=None, description="A version whose rules the new version copies"
    )


class AccountMappingUpdateIn(BaseModel):
    """``PATCH /account-mappings/{id}``: the members sent replace the stored values."""

    model_config = ConfigDict(extra="forbid")

    name: str | None = Field(default=None, max_length=LABEL_LENGTH)
    notes: str | None = Field(default=None, max_length=MEMO_LENGTH)
    effective_from: AwareDatetime | None = None  # MAIN DEFECT 4: aware only (04 SC-V timestamptz)


class AccountMappingSubmitIn(BaseModel):
    """``POST /account-mappings/{id}/submit``."""

    model_config = ConfigDict(extra="forbid")

    comment: str | None = Field(default=None, max_length=MEMO_LENGTH)


class AccountMappingOut(BaseModel):
    """A T-REF-14 version with its pending approval request and rule count (L2-1-Q-1); its author
    and publisher are API-S-Actor (04 §16.14, rev 1.139)."""

    id: uuid.UUID
    name: str
    notes: str | None
    version_no: int
    status: ConfigStatus
    effective_from: datetime | None
    effective_to: datetime | None
    content_sha256: str | None
    approval_request_id: uuid.UUID | None
    pending_approval_request_id: uuid.UUID | None
    published_at: datetime | None
    published_by: ActorOut | None
    supersedes_version_id: uuid.UUID | None
    impact_simulation_file_id: uuid.UUID | None
    rule_count: int
    created_at: datetime
    created_by: ActorOut
    updated_at: datetime
    row_version: int


class AccountMappingRuleIn(BaseModel):
    """``POST /account-mappings/{id}/rules``: a T-REF-15 rule of a DRAFT or TESTED version."""

    model_config = ConfigDict(extra="forbid")

    account_role: AccountRole
    clearing_purpose: ClearingPurpose | None = Field(
        default=None, description="Required for BILLING_CLEARING and null for every other role"
    )
    entity_id: uuid.UUID | None = Field(default=None, description="Null = any entity")
    book_code: BookCode | None = Field(default=None, description="Null = any book")
    product_id: uuid.UUID | None = None
    revenue_category: str | None = Field(default=None, max_length=CODE_LENGTH)
    gl_account_id: uuid.UUID
    default_dimensions: dict[str, Any] = Field(
        default_factory=dict, description="Dimension code → value code"
    )
    priority: int = Field(default=0, ge=INT_MIN, le=INT_MAX)


class AccountMappingRuleOut(BaseModel):
    """A T-REF-15 rule with its GL account as API-S-Ref."""

    id: uuid.UUID
    account_mapping_version_id: uuid.UUID
    account_role: AccountRole
    clearing_purpose: ClearingPurpose | None
    entity_id: uuid.UUID | None
    book_code: BookCode | None
    product_id: uuid.UUID | None
    revenue_category: str | None
    gl_account: RefOut
    default_dimensions: dict[str, Any]
    priority: int
    specificity: int


class AccountResolutionSourceOut(BaseModel):
    """The T-REF-15 step that answered: an obligation or template override (steps 1 and 2) or the
    rule of the PUBLISHED version effective at ``known_at`` (step 3)."""

    type: SourceType
    id: uuid.UUID | None = Field(description="The rule id; null for an override")
    override_key: str
    account_mapping_version_id: uuid.UUID | None
    version_no: int | None
    specificity: int | None
    priority: int | None


class AccountResolutionOut(BaseModel):
    """``GET /account-mappings/resolve``: the GL account of a role (L2-1-Q-5)."""

    role: AccountRole
    clearing_purpose: ClearingPurpose | None
    entity: RefOut | None
    book: BookCode | None
    product_id: uuid.UUID | None
    revenue_category: str | None
    known_at: datetime
    gl_account: RefOut
    default_dimensions: dict[str, Any]
    source: AccountResolutionSourceOut
