"""The ``/api/v1`` router (docs/dev-guide.md DG-API-01; 04 API-C-01)."""

from __future__ import annotations

from typing import Final

from fastapi import APIRouter

from erev_api.api.v1 import (
    access_reviews,
    accounts,
    api_clients,
    approvals,
    audit,
    calendars,
    close_checklist_templates,
    close_runs,
    combinations,
    config_test_cases,
    contracts,
    controls,
    currencies,
    customers,
    dashboard,
    dimensions,
    entities,
    estimates,
    events,
    evidence_packs,
    exceptions,
    explain,
    files,
    health,
    imports,
    integrations,
    jobs,
    journal_runs,
    judgements,
    manual_adjustments,
    me,
    migrations,
    modifications,
    oauth,
    obligations,
    operator_tenants,
    periods,
    pob_templates,
    policies,
    products,
    reconciliations,
    reports,
    roles,
    rule_sets,
    saved_views,
    schedules,
    search,
    session,
    sod,
    source_records,
    ssp_books,
    ssp_calculator,
    subledger,
    support_grants,
    tenant,
    users,
    webhooks,
)

# One router per API-R row, each tagged with its API-R id and name (DG-API-01).
ROUTERS: Final[tuple[APIRouter, ...]] = (
    session.router,
    oauth.router,
    operator_tenants.router,
    me.router,
    tenant.router,
    users.router,
    roles.router,
    api_clients.router,
    sod.router,
    support_grants.router,
    access_reviews.router,
    approvals.router,
    pob_templates.router,
    policies.router,
    rule_sets.router,
    config_test_cases.router,
    files.router,
    saved_views.router,
    entities.router,
    calendars.router,
    periods.router,
    close_checklist_templates.router,
    currencies.router,
    accounts.router,
    dimensions.router,
    customers.router,
    products.router,
    ssp_books.router,
    ssp_calculator.router,
    contracts.router,
    combinations.router,
    events.router,
    estimates.router,
    modifications.router,
    judgements.router,
    schedules.router,
    obligations.router,
    subledger.router,
    journal_runs.router,
    manual_adjustments.router,
    close_runs.router,
    reconciliations.router,
    imports.router,
    migrations.router,
    integrations.router,
    exceptions.router,
    source_records.router,
    explain.router,
    reports.router,
    evidence_packs.router,
    dashboard.router,
    search.router,
    audit.router,
    controls.router,
    webhooks.router,
    jobs.router,
    health.router,
)

api_router = APIRouter()
for resource_router in ROUTERS:
    api_router.include_router(resource_router)


def openapi_tags() -> list[dict[str, str]]:
    """The document-level tags: the API-R tag of every resource router."""
    tags = {str(tag) for resource_router in ROUTERS for tag in resource_router.tags}
    return [{"name": tag} for tag in sorted(tags)]
